Repository revanite-io/pvtr-github-repo, pull requests merged in 2025-09, with the labels that each got.

#116 ci: Update release drafter labels and patterns
  .github/release-drafter.yml
Labels: automation

#126 test: Add unit tests for splitSpdxExpression function
  evaluation_plans/osps/legal/steps_test.go
Labels: automation

#131 fix: spelling in message
  evaluation_plans/osps/quality/steps.go
Labels: fix

#135 chore(ci): build against latest stable go version
  .github/workflows/build.yaml
Labels: maintenance

#125 test: Add unit test for getLicenseList function
  evaluation_plans/osps/legal/steps.go
  evaluation_plans/osps/legal/steps_test.go
Labels: automation

#137 fix: missed some checkouts that are still persisting credentials
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  evaluation_plans/osps/build_release/steps_test.go
Labels: fix

#146 fix: QA-02.01 to return NeedsReview
  evaluation_plans/osps/quality/steps.go
Labels: fix

#142 fix: remove code check dependency for primary branch protection check
  evaluation_plans/osps/access_control/evaluations.go
  evaluation_plans/osps/access_control/steps.go
Labels: fix

#136 test: Add comprehensive unit tests for goodLicense with dependency injection
  data/rest-data.go
  data/rest_data_mock.go
  evaluation_plans/osps/legal/steps.go
  evaluation_plans/osps/legal/steps_test.go
Labels: automation

#156 feat: add support for sarif output
  go.mod
  go.sum
  main.go
Labels: feature

#162 chore(docs): update README
  .github/CONTRIBUTING.md
  README.md
  kubernetes_insights_baseline.png
Labels: maintenance

#165 feat(ci): add sbom generation
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: feature
